[package]
name = "shizen-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.10", features = ["unstable-doc", "derive"] }
libshizen = { path = "../libshizen" }
# TODO workspace versions.
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.10.0", features = ["v4"] }
