[package]
name = "shizen-dioxus-core"
version = "0.1.0"
authors = ["Brandon Pollack <brandonpollack23@gmail.com>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.5", features = ["desktop", "router"] }
tracing = "0.1.40"
dioxus-logger = "0.5.1"
libshizen = { version = "0.1.0", path = "../libshizen" }
