[package]
name = "shizen-dioxus-desktop"
version = "0.1.0"
authors = ["Brandon Pollack <brandonpollack23@gmail.com>"]
edition = "2021"

[dependencies]
shizen-dioxus-core = { path = "../shizen-dioxus-core" }

dioxus = { version = "0.5", features = ["desktop", "router"] }
tracing = "0.1.40"
dioxus-logger = "0.5.0"
